name: Generate Javadoc

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  javadoc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug - List directory structure
        run: ls -R  # Verify where pom.xml is located

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and generate Javadoc
        working-directory: SEON_6441  # Ensure Maven runs in the correct folder
        run: mvn javadoc:javadoc

      - name: Debug - List Generated Javadoc Files
        working-directory: SEON_6441
        run: ls -R target/site/apidocs || echo "Javadoc directory not found"

      - name: Deploy Javadoc to GitHub Pages
        if: success()
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: SEON_6441/target/site/apidocs  # Ensure correct Javadoc path
